language: node_js
node_js:
  - "14.17.6"
 
branches:
  only:
  - master
 
cache:
  directories:
    - node_modules
 
deploy:
  provider: heroku
  api_key: 890b9349-c2bb-4a69-b93e-39b680921b2b
  app: ci-3-gitub-travis-heroku
  run: "npm install && npm start"